Instance: PHAPI
InstanceOf: CapabilityStatement
Title: "Lighthouse Patient Health API"
Usage: #definition
* description = "This CapabilityStatement contains an example for Lighthouse Patient Health API"
* status = #draft
* date = "2024-08-20T15:41:18.761Z"
* kind = #requirements
* fhirVersion = #4.0.1
* format[0] = #xml
* format[1] = #json
* rest.mode = #server
* rest.resource[+].type = #Observation
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyObservation-virus"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologyObservation-parasite"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservation-mycobact"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservation-acidfast"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationSurgicalPathologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyObservation-fungus"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationCytopathologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationElectronMicroscopyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation-bacteria"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation-unire"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation-sputum"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation-gramstain"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/SmokingStatusObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSigns"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSignsBP"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSignsSpO2"
* rest.resource[+].type = #DiagnosticReport
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationSurgicalPathologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationCytopathologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationElectronMicroscopyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyDiagnosticReport"
* rest.resource[+].type = #Specimen
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserSpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationSurgicalPathologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationCytopathologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationElectronMicroscopySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologySpecimen"
* rest.resource[+].type = #Immunization
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImmunizationImmunization"
* rest.resource[+].type = #Procedure
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureRadiology"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureOutpatient"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureSurgery"
* rest.resource[+].type = #AllergyIntolerance
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/AllergyIntolerance"
* rest.resource[+].type = #PractitionerRole
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/PractitionerRole"
* rest.resource[+].type = #Condition
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ConditionProblem"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ConditionEncounterDiagnosis"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterInpatientCondition"
* rest.resource[+].type = #Encounter
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterOutpatient"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterInpatientEncounter"
* rest.resource[+].type = #Device
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceALead"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDevicePacemaker"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceVLead"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDevice"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceDental"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceProsthesis"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceTransmitter"
* rest.resource[+].type = #MedicationRequest
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/MedicationRequestUnsigned"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/MedicationRequestNonVA"
* rest.resource[+].type = #Appointment
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Appointment"
* rest.resource[+].type = #Patient
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Patient"
* rest.resource[+].type = #DocumentReference
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DocumentReferenceDocumentReference"
* rest.resource[+].type = #Location
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Location"
* rest.resource[+].type = #Organization
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Organization"
* rest.resource[+].type = #Practitioner
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Practitioner"