ValueSet: VSVFMaritalStatus
Title: "VF_MaritalStatus"
Description: "Navigate to [ConceptMap VF_MaritalStatus](ConceptMap-CMVFMaritalStatus.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_MaritalStatus"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#D "Divorced"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#DIVORCED "DIVORCED"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#M "Married"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#MARRIED "MARRIED"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#S "Never Married"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#NEVER_MARRIED "NEVER MARRIED"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#L "Legally Separated"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#SEPARATED "SEPARATED"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#W "Widowed"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#WIDOWED "WIDOWED"
* include http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK "unknown"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#UNKNOWN "UNKNOWN"