ValueSet: VSVFPractitionerCountry
Title: "VF_PractitionerCountry"
Description: "ValueSet for Terminology Maps VF_PractitionerCountry"
* ^experimental = true
* ^name = "VF_PractitionerCountry"
* include urn:undefined#USA "United States of America"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ALABAMA "ALABAMA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ALASKA "ALASKA"
* include urn:undefined#CAN "Canada"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ALBERTA "ALBERTA"
* include urn:undefined#ASM "American Samoa"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#AMERICAN_SAMOA "AMERICAN SAMOA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ARIZONA "ARIZONA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ARKANSAS "ARKANSAS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ARMED_FORCES_AF,EU,ME,CA "ARMED FORCES AF,EU,ME,CA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ARMED_FORCES_AMER_(EXC_CANADA) "ARMED FORCES AMER (EXC CANADA)"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ARMED_FORCES_PACIFIC "ARMED FORCES PACIFIC"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#BRITISH_COLUMBIA "BRITISH COLUMBIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#CALIFORNIA "CALIFORNIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#CANADA "CANADA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#COLORADO "COLORADO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#CONNECTICUT "CONNECTICUT"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#DELAWARE "DELAWARE"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#DISTRICT_OF_COLUMBIA "DISTRICT OF COLUMBIA"
* include urn:undefined#FSM "Federated States of Micronesia"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#FEDERATED_STATES_OF_MICRONESIA "FEDERATED STATES OF MICRONESIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#FLORIDA "FLORIDA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#GEORGIA "GEORGIA"
* include urn:undefined#GUM "Guam"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#GUAM "GUAM"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#HAWAII "HAWAII"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#IDAHO "IDAHO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ILLINOIS "ILLINOIS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#INDIANA "INDIANA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#IOWA "IOWA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#KANSAS "KANSAS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#KENTUCKY "KENTUCKY"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#LOUISIANA "LOUISIANA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MAINE "MAINE"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MANITOBA "MANITOBA"
* include urn:undefined#MHL "Marshall Islands"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MARSHALL_ISLANDS "MARSHALL ISLANDS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MARYLAND "MARYLAND"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MASSACHUSETTS "MASSACHUSETTS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MEXICO "MEXICO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MICHIGAN "MICHIGAN"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MINNESOTA "MINNESOTA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MISSISSIPPI "MISSISSIPPI"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MISSOURI "MISSOURI"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#MONTANA "MONTANA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEBRASKA "NEBRASKA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEVADA "NEVADA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEW_BRUNSWICK "NEW BRUNSWICK"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEW_HAMPSHIRE "NEW HAMPSHIRE"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEW_JERSEY "NEW JERSEY"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEW_MEXICO "NEW MEXICO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEW_YORK "NEW YORK"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NEWFOUNDLAND "NEWFOUNDLAND"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NORTH_CAROLINA "NORTH CAROLINA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NORTH_DAKOTA "NORTH DAKOTA"
* include urn:undefined#MNP "Northern Mariana Islands"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NORTHERN_MARIANA_ISLANDS "NORTHERN MARIANA ISLANDS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NORTHWEST_TERRITORIES "NORTHWEST TERRITORIES"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NOVA_SCOTIA "NOVA SCOTIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#NUNAVUT_PROVINCE "NUNAVUT PROVINCE"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#OHIO "OHIO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#OKLAHOMA "OKLAHOMA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#ONTARIO "ONTARIO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#OREGON "OREGON"
* include urn:undefined#PLW "Palau"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#PALAU "PALAU"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#PENNSYLVANIA "PENNSYLVANIA"
* include urn:undefined#PHL "Phillipines"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#PHILIPPINES "PHILIPPINES"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#PRINCE_EDWARD_ISLAND "PRINCE EDWARD ISLAND"
* include urn:undefined#PRI "Puerto Rico"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#PUERTO_RICO "PUERTO RICO"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#QUEBEC "QUEBEC"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#RHODE_ISLAND "RHODE ISLAND"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#SASKATCHEWAN "SASKATCHEWAN"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#SOUTH_CAROLINA "SOUTH CAROLINA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#SOUTH_DAKOTA "SOUTH DAKOTA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#TENNESSEE "TENNESSEE"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#TEXAS "TEXAS"
* include urn:undefined#UMI "U.S. Minor Outlying Islands"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#U.S._MINOR_OUTLYING_ISLANDS "U.S. MINOR OUTLYING ISLANDS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#UTAH "UTAH"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#VERMONT "VERMONT"
* include urn:undefined#VIR "Virgin Islands"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#VIRGIN_ISLANDS "VIRGIN ISLANDS"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#VIRGINIA "VIRGINIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#WASHINGTON "WASHINGTON"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#WEST_VIRGINIA "WEST VIRGINIA"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#WISCONSIN "WISCONSIN"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#WYOMING "WYOMING"
* include http://va.gov/terminology/vistaDefinedTerms/200-.1215#YUKON_TERRITORY "YUKON TERRITORY"