ValueSet: VSVFVitalsPosition
Title: "VF_VitalsPosition"
Description: "Navigate to [ConceptMap VF_VitalsPosition](ConceptMap-CMVFVitalsPosition.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_VitalsPosition"
* include http://snomed.info/sct#102536004 "Left lateral decubitus position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#5335366 "LEFT LATERAL RECUMBENT"
* include http://snomed.info/sct#102538003 "Recumbent body position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4688663 "LYING"
* include http://snomed.info/sct#1240000 "Prone body position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#5335362 "PRONE"
* include http://snomed.info/sct#102535000 "Right lateral decubitus position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#5335364 "RIGHT LATERAL RECUMBENT"
* include http://snomed.info/sct#426408003 "Semi-Fowler's position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4688682 "SEMIFOWLERS"
* include http://snomed.info/sct#33586001 "Sitting position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4688703 "SITTING"
* include http://snomed.info/sct#10904000 "Orthostatic body position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4688707 "STANDING"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4500643 "STANDING WEIGHT"
* include http://snomed.info/sct#34106002 "Trendelenburg position (finding)"
* include http://va.gov/terminology/vistaDefinedElements/120.5-5#4688694 "TRENDELENBURG"