ValueSet: VSVFReligion
Title: "VF_Religion"
Description: "Navigate to [ConceptMap VF_Religion](ConceptMap-CMVFReligion.html)"
* ^experimental = true
* ^name = "VF_Religion"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#9 "ADVENTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#32 "AFRICAN RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#33 "AFRO-CARIBBEAN RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#34 "AGNOSTICISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#35 "ANGLICAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#36 "ANIMISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#10 "ASSEMBLY OF GOD"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#37 "ATHEISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#38 "BABI &amp; BAHA'I FAITHS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#3 "BAPTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#39 "BON"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#11 "BRETHREN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#40 "CAO DAI"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#41 "CELTICISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#42 "CHRISTIAN (NON-SPECIFIC)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#12 "CHRISTIAN SCIENTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#13 "CHURCH OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#14 "CHURCH OF GOD"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#43 "CONFUCIANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#44 "CONGREGATIONAL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#45 "CYBERCULTURE RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#15 "DISCIPLES OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#46 "DIVINATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#2 "EASTERN ORTHODOX"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#8 "EPISCOPALIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#16 "EVANGELICAL COVENANT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#47 "FOURTH WAY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#48 "FREE DAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#17 "FRIENDS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#49 "FULL GOSPEL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#50 "GNOSIS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#51 "HINDUISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#52 "HUMANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#53 "INDEPENDENT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#20 "ISLAM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#54 "JAINISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#18 "JEHOVAH'S WITNESSES"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#1 "JUDAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#19 "LATTER DAY SAINTS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#5 "LUTHERAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#55 "MAHAYANA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#56 "MEDITATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#57 "MESSIANIC JUDAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#4 "METHODIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#58 "MITRAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#30 "NATIVE AMERICAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#21 "NAZARENE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#59 "NEW AGE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#60 "NON-ROMAN CATHOLIC"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#61 "OCCULT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#62 "ORTHODOX"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#63 "PAGANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#23 "PENTECOSTAL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#6 "PRESBYTERIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#64 "PROCESS, THE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#24 "PROTESTANT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#25 "PROTESTANT, NO DENOMINATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#26 "REFORMED"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#65 "REFORMED/PRESBYTERIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#0 "ROMAN CATHOLIC CHURCH"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#27 "SALVATION ARMY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#66 "SATANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#67 "SCIENTOLOGY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#68 "SHAMANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#69 "SHIITE (ISLAM)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#70 "SHINTO"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#71 "SIKISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#72 "SPIRITUALISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#73 "SUNNI (ISLAM)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#74 "TAOISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#75 "THERAVADA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#28 "UNITARIAN-UNIVERSALISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#7 "UNITED CHURCH OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#76 "UNIVERSAL LIFE CHURCH"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#77 "VAJRAYANA (TIBETAN)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#78 "VEDA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#79 "VOODOO"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#80 "WICCA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#81 "YAOHUSHUA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#31 "ZEN BUDDHISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#82 "ZOROASTRIANISM"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1001 "Adventist"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1002 "African Religions"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1003 "Afro-Caribbean Religions"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1004 "Agnosticism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1005 "Anglican"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1006 "Animism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1061 "Assembly of God"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1007 "Atheism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1008 "Babi & Baha'I faiths"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1009 "Baptist"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1010 "Bon"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1062 "Brethren"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1011 "Cao Dai"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1012 "Celticism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1013 "Christian (non-Catholic, non-specific)"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1063 "Christian Scientist"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1064 "Church of Christ"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1065 "Church of God"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1014 "Confucianism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1066 "Congregational"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1015 "Cyberculture Religions"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1067 "Disciples of Christ"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1016 "Divination"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1068 "Eastern Orthodox"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1069 "Episcopalian"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1070 "Evangelical Covenant"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1017 "Fourth Way"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1018 "Free Daism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1071 "Friends"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1072 "Full Gospel"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1019 "Gnosis"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1020 "Hinduism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1021 "Humanism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1022 "Independent"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1023 "Islam"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1024 "Jainism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1025 "Jehovah's Witnesses"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1026 "Judaism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1027 "Latter Day Saints"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1028 "Lutheran"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1029 "Mahayana"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1030 "Meditation"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1031 "Messianic Judaism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1073 "Methodist"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1032 "Mitraism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1074 "Native American"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1075 "Nazarene"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1033 "New Age"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1034 "non-Roman Catholic"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1035 "Occult"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1036 "Orthodox"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1037 "Paganism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1038 "Pentecostal"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1076 "Presbyterian"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1039 "Process, The"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1077 "Protestant"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1078 "Protestant, No Denomination"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1079 "Reformed"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1040 "Reformed/Presbyterian"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1041 "Roman Catholic Church"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1080 "Salvation Army"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1042 "Satanism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1043 "Scientology"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1044 "Shamanism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1045 "Shiite (Islam)"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1046 "Shinto"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1047 "Sikism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1048 "Spiritualism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1049 "Sunni (Islam)"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1050 "Taoism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1051 "Theravada"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1052 "Unitarian-Universalism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1082 "United Church of Christ"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1053 "Universal Life Church"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1054 "Vajrayana (Tibetan)"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1055 "Veda"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1056 "Voodoo"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1057 "Wicca"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1058 "Yaohushua"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1059 "Zen Buddhism"
* include http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation#1060 "Zoroastrianism"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#83 "ASKED BUT DECLINED TO ANSWER"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#22 "OTHER"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#29 "UNKNOWN/NO PREFERENCE"
* include http://terminology.hl7.org/CodeSystem/v3-NullFlavor#ASKU "asked but unknown"
* include http://terminology.hl7.org/CodeSystem/v3-NullFlavor#OTH "other"
* include http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK "unknown"