ValueSet: VSVFRadiologyProcedureStatus
Title: "VF_RadiologyProcedureStatus"
Description: "ValueSet for Terminology Maps VF_RadiologyProcedureStatus"
* ^experimental = true
* ^name = "VF_RadiologyProcedureStatus"
* include http://hl7.org/fhir/event-status#preparation "Preparation"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#CALLED_FOR_EXAM "CALLED FOR EXAM"
* include http://hl7.org/fhir/event-status#not-done "Not Done"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#CANCELLED "CANCELLED"
* include http://hl7.org/fhir/event-status#completed "Completed"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#COMPLETE "COMPLETE"
* include http://hl7.org/fhir/event-status#in-progress "In Progress"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#EXAMINED "EXAMINED"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#TRANSCRIBED "TRANSCRIBED"
* include http://va.gov/terminology/vistaDefinedTerms/72-.01#WAITING_FOR_EXAM "WAITING FOR EXAM"