ValueSet: VSVFVitalsDevice
Title: "VF_VitalsDevice"
Description: "ValueSet for Terminology Maps VF_VitalsDevice"
* ^experimental = true
* ^name = "VF_VitalsDevice"
* include http://snomed.info/sct#466289007 "Bed scale (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688641 "BED"
* include http://snomed.info/sct#243142003 "Dual pressure spontaneous ventilation support (regime/therapy)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688695 "BIPAP (BI-LEVEL POSITIVE AIRWAY PRESSURE)"
* include http://snomed.info/sct#229306004 "Positive pressure therapy (regime/therapy)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688691 "BIPAP-CPAP (BI-LEVEL POSITIVE AIRWAY PRESSURE-CONTINUOUS POSITIVE AIRWAY PRESSURE)"
* include http://snomed.info/sct#467496001 "Chair scale, mechanical (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688646 "CHAIR"
* include http://snomed.info/sct#243147009 "Controlled ventilation (procedure)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688647 "CONTROLLED VENTILATOR"
* include http://snomed.info/sct#47545007 "Continuous positive airway pressure ventilation treatment (regime/therapy)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688690 "CPAP (CONTINUOUS POSITIVE AIRWAY PRESSURE)"
* include http://snomed.info/sct#445949006 "Electronic sphygmomanometer (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688649 "CUFF-AUTOMATED (AUTOMATED CUFF)"
* include http://snomed.info/sct#464069000 "Mercury manual sphygmomanometer (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688688 "CUFF-MANUAL (MANUAL CUFF)"
* include http://snomed.info/sct#43770009 "Doppler device (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688650 "DOPPLER"
* include http://snomed.info/sct#426294006 "Face tent oxygen delivery device (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688654 "FACE TENT"
* include http://snomed.info/sct#257268009 "Laryngeal mask (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4536584 "LARYNGEAL MASK AIRWAY"
* include http://snomed.info/sct#257467001 "Electrocardiogram lead (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688659 "LEAD"
* include http://snomed.info/sct#255509001 "Large (qualifier value)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688661 "LG ADULT CUFF"
* include http://snomed.info/sct#462242008 "Patient sling scale (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688684 "LIFT SCALE"
* include http://snomed.info/sct#336602003 "Oxygen mask (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688664 "MASK"
* include http://snomed.info/sct#706767009 "Patient data recorder (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688665 "MONITOR"
* include http://snomed.info/sct#336623009 "Oxygen nasal cannula (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688687 "MUSTACHE CANNULA"
* include http://terminology.hl7.org/CodeSystem/VHA#4688666 "NASAL CANNULA"
* include http://snomed.info/sct#427591007 "Nonrebreather oxygen mask (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688667 "NON RE-BREATHER"
* include http://snomed.info/sct#425926003 "Partial rebreather oxygen mask (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4711338 "PARTIAL RE-BREATHER (PARTIAL REBREATHER)"
* include http://snomed.info/sct#67822003 "Child (person)"
* include http://terminology.hl7.org/CodeSystem/VHA#4711339 "PEDIATRIC CUFF"
* include http://terminology.hl7.org/CodeSystem/VHA#4711340 "PENDANT CANNULA"
* include http://terminology.hl7.org/CodeSystem/VHA#4693051 "RESERVOIR CANNULA"
* include http://snomed.info/sct#255507004 "Small (qualifier value)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688705 "SM ADULT CUFF"
* include http://snomed.info/sct#118712001 "Procedure on thigh (procedure)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688709 "THIGH CUFF"
* include http://snomed.info/sct#6097006 "T-tube, device (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688710 "T-PIECE"
* include http://snomed.info/sct#465839001 "Tracheostomy mask, oxygen (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688711 "TRACHEOSTOMY COLLAR"
* include http://snomed.info/sct#40617009 "Artificial respiration (procedure)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688715 "VENTILATOR"
* include http://snomed.info/sct#465433006 "Venturi oxygen face mask (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688716 "VENTURI MASK"
* include http://snomed.info/sct#466532009 "Wheelchair scale (physical object)"
* include http://terminology.hl7.org/CodeSystem/VHA#4688693 "WHEELCHAIR SCALE"