ValueSet: VSVFReligion
Title: "VF_Religion"
Description: "Navigate to [ConceptMap VF_Religion](ConceptMap-CMVFReligion.html)"
* ^experimental = true
* include http://va.gov/terminology/vistaDefinedElements/2-.08#9 "ADVENTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#32 "AFRICAN RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#33 "AFRO-CARIBBEAN RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#34 "AGNOSTICISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#35 "ANGLICAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#36 "ANIMISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#10 "ASSEMBLY OF GOD"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#37 "ATHEISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#38 "BABI &amp; BAHA'I FAITHS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#3 "BAPTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#39 "BON"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#11 "BRETHREN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#40 "CAO DAI"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#41 "CELTICISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#42 "CHRISTIAN (NON-SPECIFIC)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#12 "CHRISTIAN SCIENTIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#13 "CHURCH OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#14 "CHURCH OF GOD"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#43 "CONFUCIANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#44 "CONGREGATIONAL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#45 "CYBERCULTURE RELIGIONS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#15 "DISCIPLES OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#46 "DIVINATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#2 "EASTERN ORTHODOX"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#8 "EPISCOPALIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#16 "EVANGELICAL COVENANT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#47 "FOURTH WAY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#48 "FREE DAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#17 "FRIENDS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#49 "FULL GOSPEL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#50 "GNOSIS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#51 "HINDUISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#52 "HUMANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#53 "INDEPENDENT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#20 "ISLAM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#54 "JAINISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#18 "JEHOVAH'S WITNESSES"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#1 "JUDAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#19 "LATTER DAY SAINTS"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#5 "LUTHERAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#55 "MAHAYANA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#56 "MEDITATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#57 "MESSIANIC JUDAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#4 "METHODIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#58 "MITRAISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#30 "NATIVE AMERICAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#21 "NAZARENE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#59 "NEW AGE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#60 "NON-ROMAN CATHOLIC"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#61 "OCCULT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#62 "ORTHODOX"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#63 "PAGANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#23 "PENTECOSTAL"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#6 "PRESBYTERIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#64 "PROCESS, THE"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#24 "PROTESTANT"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#25 "PROTESTANT, NO DENOMINATION"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#26 "REFORMED"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#65 "REFORMED/PRESBYTERIAN"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#0 "ROMAN CATHOLIC CHURCH"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#27 "SALVATION ARMY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#66 "SATANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#67 "SCIENTOLOGY"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#68 "SHAMANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#69 "SHIITE (ISLAM)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#70 "SHINTO"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#71 "SIKISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#72 "SPIRITUALISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#73 "SUNNI (ISLAM)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#74 "TAOISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#75 "THERAVADA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#28 "UNITARIAN-UNIVERSALISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#7 "UNITED CHURCH OF CHRIST"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#76 "UNIVERSAL LIFE CHURCH"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#77 "VAJRAYANA (TIBETAN)"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#78 "VEDA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#79 "VOODOO"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#80 "WICCA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#81 "YAOHUSHUA"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#31 "ZEN BUDDHISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#82 "ZOROASTRIANISM"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#83 "ASKED BUT DECLINED TO ANSWER"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#22 "OTHER"
* include http://va.gov/terminology/vistaDefinedElements/2-.08#29 "UNKNOWN/NO PREFERENCE"