ValueSet: VSVFimmunizationStatusReason
Title: "VF_immunizationStatusReason"
Description: "Navigate to [ConceptMap VF_immunizationStatusReason](ConceptMap-CMVFimmunizationStatusReason.html)"
* ^experimental = true
* ^name = "VF_immunizationStatusReason"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "DECLINED FLU IMM (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "DECLINED PNEUMOCOCCAL (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "DECLINED TETANUS/DIPT (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "DECLINES FLU VAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "DECLINES PNEUMOVAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "FLU REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "FLU VAC NOT AVAILABLE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "FLU VACCINE REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "INFLUENZA CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "INFLUENZA CONTRAINDICATED (PERM) (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "INFLUENZA REFUSED/DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "Influenza Vaccination (Refused) (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "INFLUENZA VACCINE CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "PNEUMOCOCCAL REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "PNEUMOVAX CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "PNEUMOVAX DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "PNEUMOVAX REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "PNEUMOVAX REFUSED/DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED FLU (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED HPV VACCINE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED INFLUENZA VACCINE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED PNEUMOVAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED TETANUS (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "REFUSED-INFLUENZA (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "TET TOX CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "TETANUS CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "TETANUS DIPHTHERIA-VACCINE NOT AVAILABLE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "TETANUS REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "V7-INFLUENZA NOT AVAILABLE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "V7-PNEUMOVAX NOT AVAILABLE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#null "ZZPNEUMOCOCCAL REFUSED (HISTORICAL)"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#MEDPREC "medical precaution"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#OSTOCK "product out of stock"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#OSTOCK "product out of stock"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#OSTOCK "product out of stock"
* include http://terminology.hl7.org/CodeSystem/v3-ActReason#PATOBJ "patient objection"