ValueSet: VSVFImageStatusRadNuc
Title: "VF_ImageStatusRadNuc"
Description: "Navigate to [ConceptMap VF_ImageStatusRadNuc](ConceptMap-CMVFImageStatusRadNuc.html)"
* ^experimental = true
* ^name = "VF_ImageStatusRadNuc"
* include http://va.gov/terminology/vistaDefinedElements/74-5#X "DELETED"
* include http://va.gov/terminology/vistaDefinedElements/74-5#D "DRAFT"
* include http://va.gov/terminology/vistaDefinedElements/74-5#EF "ELECTRONICALLY FILED"
* include http://va.gov/terminology/vistaDefinedElements/74-5#PD "PROBLEM DRAFT"
* include http://va.gov/terminology/vistaDefinedElements/74-5#R "RELEASED/NOT VERIFIED"
* include http://va.gov/terminology/vistaDefinedElements/74-5#V "VERIFIED"
* include http://hl7.org/fhir/ValueSet/observation-status#cancelled "Cancelled"
* include http://hl7.org/fhir/ValueSet/observation-status#preliminary "Preliminary"
* include http://hl7.org/fhir/ValueSet/observation-status#preliminary "Preliminary"
* include http://hl7.org/fhir/ValueSet/observation-status#preliminary "Preliminary"
* include http://hl7.org/fhir/ValueSet/observation-status#preliminary "Preliminary"
* include http://hl7.org/fhir/ValueSet/observation-status#final "Final"