ValueSet: VSVFImmunizationReaction
Title: "VF_ImmunizationReaction"
Description: "Navigate to [ConceptMap VF_ImmunizationReaction](ConceptMap-CMVFImmunizationReaction.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_ImmunizationReaction"
* include http://snomed.info/sct#293104008 "Adverse reaction to component of vaccine product (disorder)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#9 "ANAPHYLAXIS OR COLLAPSE"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#8 "ARTHRITIS OR ARTHRALGIAS"
* include http://snomed.info/sct#91175000 "Seizure (finding)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#7 "CONVULSIONS"
* include http://snomed.info/sct#386661006 "Fever (finding)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#1 "FEVER"
* include http://snomed.info/sct#55929007 "Feeling irritable (finding)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#2 "IRRITABILITY"
* include http://snomed.info/sct#214264003 "Lethargy (finding)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#6 "LETHARGY"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#3 "LOCAL REACTION OR SWELLING"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#11 "OTHER"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#5 "RASH OR ITCHING"
* include http://snomed.info/sct#271825005 "Respiratory distress (finding)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#10 "RESPIRATORY DISTRESS"
* include http://snomed.info/sct#422400008 "Vomiting (disorder)"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#4 "VOMITING"
* include http://loinc.org#LA137-2 "None"
* include http://va.gov/terminology/vistaDefinedElements/9000010.11-.06#NONE "NONE"