ValueSet: VSVFImageStatus
Title: "VF_ImageStatus"
* ^experimental = true
* ^name = "VF_ImageStatus"
* include http://hl7.org/fhir/observation-status#preliminary "Preliminary"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#D "DRAFT"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#PD "PROBLEM DRAFT"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#RNV "RELEASED NOT VERIFIED"
* include http://hl7.org/fhir/observation-status#final "Final"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#ROV "RELEASED OFF-LINE VERIFIED"
* include http://hl7.org/fhir/observation-status#amended "Amended"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#SROV "RELEASED OFF-LINE VERIFIED OF SUPERSEDED"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#RV "RELEASED ON-LINE VERIFIED"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#SRV "RELEASED ON-LINE VERIFIED OF SUPERSEDED"
* include http://va.gov/terminology/vistaDefinedTerms/691.5-1506#S "SUPERSEDED"