ValueSet: VSVFImageStatus
Title: "VF_ImageStatus"
Description: "Navigate to [ConceptMap VF_ImageStatus](ConceptMap-CMVFImageStatus.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_ImageStatus"
* include http://hl7.org/fhir/observation-status#preliminary "Preliminary"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#D "DRAFT"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#PD "PROBLEM DRAFT"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#RNV "RELEASED NOT VERIFIED"
* include http://hl7.org/fhir/observation-status#final "Final"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#ROV "RELEASED OFF-LINE VERIFIED"
* include http://hl7.org/fhir/observation-status#amended "Amended"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#SROV "RELEASED OFF-LINE VERIFIED OF SUPERSEDED"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#RV "RELEASED ON-LINE VERIFIED"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#SRV "RELEASED ON-LINE VERIFIED OF SUPERSEDED"
* include http://va.gov/terminology/vistaDefinedElements/691.5-1506#S "SUPERSEDED"