ValueSet: VSVFDiagnosticReportLabStatus
Title: "VF_DiagnosticReportLabStatus"
Description: "Navigate to [ConceptMap VF_DiagnosticReportLabStatus](ConceptMap-CMVFDiagnosticReportLabStatus.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_DiagnosticReportLabStatus"
* include http://hl7.org/fhir/diagnostic-report-status#corrected "Corrected"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#C "CORRECTED RESULTS"
* include http://hl7.org/fhir/diagnostic-report-status#final "Final"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#F "FINAL RESULTS"
* include http://hl7.org/fhir/diagnostic-report-status#unknown "Unknown"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#Y "NO ORDER ON RECORD"
* include http://hl7.org/fhir/diagnostic-report-status#preliminary "Preliminary"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#R "NOT VERIFIED"
* include http://hl7.org/fhir/diagnostic-report-status#cancelled "Cancelled"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#X "ORDER CANCELED"
* include http://hl7.org/fhir/diagnostic-report-status#registered "Registered"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#O "ORDER RECIEVED"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#P "PRELIMINARY"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#S "PROCEDURE SCHEDULED"
* include http://hl7.org/fhir/diagnostic-report-status#partial "Partial"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#A "SOME RESULTS AVAILABLE"
* include http://va.gov/terminology/vistaDefinedElements/63.53-10#I "SPECIMEN RECEIVED"