ValueSet: VSVFdeviceTypePacemaker
Title: "VF_deviceTypePacemaker"
Description: "Navigate to [ConceptMap VF_deviceTypePacemaker](ConceptMap-CMVFdeviceTypePacemaker.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_deviceTypePacemaker"
* include http://snomed.info/sct#360129009 "Cardiac pacemaker lead (physical object)"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#A "'A' FOR A LEAD;"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#AV "'AV' FOR BOTH A LEAD AND V LEAD;"
* include http://snomed.info/sct#118378005 "Pacemaker pulse generator, device (physical object)"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#G "'G' FOR GENERATOR;"
* include http://snomed.info/sct#303476002 "Cardiovascular equipment (physical object)"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#P "'P' FOR PSA ANALYZER;"
* include http://snomed.info/sct#706635000 "Telephone transmitter/receiver system (physical object)"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#T "'T' FOR TELEPHONE TRANSMITTER;"
* include http://va.gov/terminology/vistaDefinedElements/698.4-1#V "'V' FOR V LEAD;"