ValueSet: VSVFRadiologyProcedureStatus
Title: "VF_RadiologyProcedureStatus"
Description: "Navigate to [ConceptMap VF_RadiologyProcedureStatus](ConceptMap-CMVFRadiologyProcedureStatus.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_RadiologyProcedureStatus"
* include http://hl7.org/fhir/event-status#preparation "Preparation"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#CALLED_FOR_EXAM "CALLED FOR EXAM"
* include http://hl7.org/fhir/event-status#not-done "Not Done"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#CANCELLED "CANCELLED"
* include http://hl7.org/fhir/event-status#completed "Completed"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#COMPLETE "COMPLETE"
* include http://hl7.org/fhir/event-status#in-progress "In Progress"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#EXAMINED "EXAMINED"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#TRANSCRIBED "TRANSCRIBED"
* include http://va.gov/terminology/vistaDefinedElements/72-.01#WAITING_FOR_EXAM "WAITING FOR EXAM"