ValueSet: VSVFOutMedRequestStatus
Title: "VF_OutMedRequestStatus"
Description: "Navigate to [ConceptMap VF_OutMedRequestStatus](ConceptMap-CMVFOutMedRequestStatus.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_OutMedRequestStatus"
* include http://hl7.org/fhir/CodeSystem/medicationrequest-status#active "active"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#0 "ACTIVE"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#NULL "ACTIVE"
* include http://hl7.org/fhir/CodeSystem/medicationrequest-status#entered-in-error "entered-in-error"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#13 "DELETED"
* include http://hl7.org/fhir/CodeSystem/medicationrequest-status#stopped "stopped"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#12 "DISCONTINUED"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#15 "DISCONTINUED (EDIT)"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#14 "DISCONTINUED BY PROVIDER"
* include http://hl7.org/fhir/CodeSystem/medicationrequest-status#draft "draft"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#4 "DRUG INTERACTIONS"
* include http://hl7.org/fhir/CodeSystem/medicationrequest-status#completed "completed"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#11 "EXPIRED"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#3 "HOLD"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#1 "NON-VERIFIED"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#16 "PROVIDER HOLD"
* include http://va.gov/terminology/vistaDefinedTerms/52-100#5 "SUSPENDED"