ValueSet: VSVFSourceOfAdmission
Title: "VF_SourceOfAdmission"
Description: "Navigate to [ConceptMap VF_SourceOfAdmission](ConceptMap-CMVFSourceOfAdmission.html)"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1K "ALL OTHER NON VA HOSP NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4Y "ALL OTHER SOURCES, UNKNOWN OR NO INFO"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1H "COMMUNITY NURSING HOME NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1G "CONTRACT CNH (UNDER VA AUSPICES)"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#7B "DIRECT ADM OF ACTIVE DUTY PERS FROM MILT HOSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#6A "DIRECT ADMISSION FROM A VA HOSPITAL"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5G "DIRECT ADMISSION FROM ALL OTHER SOURCES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#6D "DIRECT ADMISSION FROM ALL OTHER SOURCES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4D "FROM ANOTHER VA DOM"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4G "FROM COMMUNITY HOSPITAL NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4F "FROM COMMUNITY HOSPITAL UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4J "FROM COMMUNITY NURSING HOME NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4H "FROM COMMUNITY NURSING HOME UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4M "FROM MILITARY HOSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4P "FROM OTHER FEDERAL HOSP NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4N "FROM OTHER FEDERAL HOSP UNDER VA AUSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4Q "FROM OTHER GOV HOSP(NON FED) NOT UNDER VA AUSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4K "FROM STATE HOME DOM"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4L "FROM STATE NURSING HOME CARE"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4A "FROM VA HOSPITAL"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4B "FROM VA HOSPITAL ON NON-BED-CARE"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4C "FROM VA NURSING HOME CARE UNIT"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1J "GOVNT(NON FED) MENTAL HOSP NOT UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#2C "MILITARY PERS BY TRANSFER FROM A MILT HOSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#2B "MILITARY PERS NOT DIRECTLY FROM MILT HOSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5B "NON-VA HOSPITAL UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#2A "NON-VETERAN OTHER THAN MILITARY"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1T "OBSERVATION AND EXAMINATION"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1M "OTHER DIRECT"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4R "OTHER GOVERNMENT HOSP(NON FED) UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1P "OUTPATIENT TREATMENT"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4U "REFERRED BY NATIONAL SERV ORGAN (LOCAL OR REG)"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4S "REFERRED BY OUTPATIENT CLINIC"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4T "REFERRED BY WELFARE AGENCY(LOCAL OR REGIONAL)"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1R "RESEARCH - VETERAN"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1S "RESEARCH NON-VETERAN"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4W "SELF-WALKIN"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1L "STATE HOME (DOM OR NHC)"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#4E "TRANS FROM DOM-DOM-CONT DOM SINCE 7/1/86 OR PRIOR"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5D "TRANS FROM NHCU-NHCU-CONT NH SINCE 7/1/86 OR PRIOR"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#3E "TRANS FROM VAH-VAH-CONT HOS SINCE 7/1/86 OR PRIOR"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#3D "TRANS FROM VAMC TO MILITARY FAC. UNDER VA AUSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#6C "TRANS IN FROM ANOTHER CNH UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#3C "TRANS IN FROM ANY OTHER NON-VA HOSP UNDER VA AUSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#6B "TRANSFER IN FROM A VA NHCU"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#3A "TRANSFER IN FROM ANOTHER VA HOSPITAL"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5E "TRANSFER IN FROM ANOTHER VA NHCU"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5F "TRANSFER IN FROM COMMUNITY HOME UNDER VA AUSPICES"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#3B "TRANSFER IN FROM OTH FED HOSP UNDER VA AUSP"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1E "VA DOMICILLARY"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5C "VA DOMICILLARY"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#5A "VA MEDICAL CENTER"
* include http://va.gov/terminology/vistaDefinedElements/45.1-.01#1D "VA NURSING HOME CARE UNIT"