ValueSet: VSVFgenderIdentity
Title: "VF_genderIdentity"
Description: "Navigate to [ConceptMap VF_genderIdentity](ConceptMap-CMVFgenderIdentity.html)"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#N "DOES NOT WISH TO DISCLOSE"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#F "FEMALE"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#M "MALE"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#B "NON-BINARY"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#O "OTHER"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#TF "TRANSGENDER FEMALE"
* include http://va.gov/terminology/vistaDefinedElements/2-.024#TM "TRANSGENDER MALE"