ValueSet: VSVFinferredCVX
Title: "VF_inferredCVX"
Description: "Navigate to [ConceptMap VF_inferredCVX](ConceptMap-CMVFinferredCVX.html)\n\n> Note that the FHIR binding is to the codes in the fhir system. The codes from the VistADefinedElements system are map source codes: they may be included in addition to the fhir codes, but they don't address the binding requirement."
* ^experimental = true
* ^name = "VF_inferredCVX"
* include http://hl7.org/fhir/sid/cvx#88 
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#DECLINED_FLU_IMM__HISTORICAL_ "DECLINED FLU IMM (HISTORICAL)"
* include http://hl7.org/fhir/sid/cvx#109 
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#DECLINED_PNEUMOCOCCAL__HISTORICAL_ "DECLINED PNEUMOCOCCAL (HISTORICAL)"
* include http://hl7.org/fhir/sid/cvx#139 
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#DECLINED_TETANUS_DIPT__HISTORICAL_ "DECLINED TETANUS/DIPT (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#DECLINES_FLU_VAX__HISTORICAL_ "DECLINES FLU VAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#DECLINES_PNEUMOVAX__HISTORICAL_ "DECLINES PNEUMOVAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#FLU_REFUSED__HISTORICAL_ "FLU REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#FLU_VAC_NOT_AVAILABLE__HISTORICAL_ "FLU VAC NOT AVAILABLE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#FLU_VACCINE_REFUSED__HISTORICAL_ "FLU VACCINE REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#INFLUENZA_CONTRAINDICATED__HISTORICAL_ "INFLUENZA CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#INFLUENZA_CONTRAINDICATED__PERM___HISTORICAL_ "INFLUENZA CONTRAINDICATED (PERM) (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#INFLUENZA_REFUSED_DECLINED__HISTORICAL_ "INFLUENZA REFUSED/DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#Influenza_Vaccination__Refused___HISTORICAL_ "Influenza Vaccination (Refused) (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#INFLUENZA_VACCINE_CONTRAINDICATED__HISTORICAL_ "INFLUENZA VACCINE CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOCOCCAL_REFUSED__HISTORICAL_ "PNEUMOCOCCAL REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOVAX_CONTRAINDICATED__HISTORICAL_ "PNEUMOVAX CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOVAX_DECLINED__HISTORICAL_ "PNEUMOVAX DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOVAX_REFUSED__HISTORICAL_ "PNEUMOVAX REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOVAX_REFUSED_DECLINED__HISTORICAL_ "PNEUMOVAX REFUSED/DECLINED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#PNEUMOVAX_ALLERGY__HISTORICAL_ "PNEUMOVAX-ALLERGY (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_FLU__HISTORICAL_ "REFUSED FLU (HISTORICAL)"
* include http://hl7.org/fhir/sid/cvx#137 
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_HPV_VACCINE__HISTORICAL_ "REFUSED HPV VACCINE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_INFLUENZA_VACCINE__HISTORICAL_ "REFUSED INFLUENZA VACCINE (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_PNEUMOVAX__HISTORICAL_ "REFUSED PNEUMOVAX (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_TETANUS__HISTORICAL_ "REFUSED TETANUS (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#REFUSED_INFLUENZA__HISTORICAL_ "REFUSED-INFLUENZA (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#TET_TOX_CONTRAINDICATED__HISTORICAL_ "TET TOX CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#TETANUS_CONTRAINDICATED__HISTORICAL_ "TETANUS CONTRAINDICATED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#TETANUS_REFUSED__HISTORICAL_ "TETANUS REFUSED (HISTORICAL)"
* include http://va.gov/terminology/vistaDefinedElements/9999999.14-.01#ZZPNEUMOCOCCAL_REFUSED__HISTORICAL_ "ZZPNEUMOCOCCAL REFUSED (HISTORICAL)"