ValueSet: VSVFMaritalStatus
Title: "VF_MaritalStatus"
Description: "Navigate to [ConceptMap VF_MaritalStatus](ConceptMap-CMVFMaritalStatus.html)"
* ^experimental = true
* ^name = "VF_MaritalStatus"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#DIVORCED "DIVORCED"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#MARRIED "MARRIED"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#NEVER_MARRIED "NEVER MARRIED"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#SEPARATED "SEPARATED"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#WIDOWED "WIDOWED"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#D "Divorced"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#M "Married"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#S "Never Married"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#L "Legally Separated"
* include http://terminology.hl7.org/CodeSystem/v3-MaritalStatus#W "Widowed"
* include http://va.gov/terminology/vistaDefinedElements/2-.05#UNKNOWN "UNKNOWN"
* include http://terminology.hl7.org/CodeSystem/v3-NullFlavor#UNK "unknown"