ValueSet: VSVFVitalsCodes
Title: "VF_VitalsCodes"
Description: "ValueSet for Terminology Maps VF_VitalsCodes"
* ^experimental = true
* ^name = "VF_VitalsCodes"
* include http://loinc.org#28615-3 "Audiology study"
* include http://terminology.hl7.org/CodeSystem/VHA#4688718 "AUDIOMETRY"
* include http://loinc.org#85354-9 "Blood pressure panel with all children optional"
* include http://terminology.hl7.org/CodeSystem/VHA#4500634 "BLOOD PRESSURE"
* include http://loinc.org#39156-5 "Body mass index (BMI) [Ratio]"
* include http://terminology.hl7.org/CodeSystem/VHA#4536993 "BODY MASS INDEX"
* include http://loinc.org#8591-0 "Central venous pressure (CVP) Mean"
* include http://terminology.hl7.org/CodeSystem/VHA#4688719 "CENTRAL VENOUS PRESSURE"
* include http://loinc.org#9844-2 "Body region Circumference"
* include http://terminology.hl7.org/CodeSystem/VHA#4688720 "CIRCUMFERENCE/GIRTH"
* include http://loinc.org#11616-0 "Fetal Heart Narrative Activity US"
* include http://terminology.hl7.org/CodeSystem/VHA#4688721 "FETAL HEART TONES"
* include http://loinc.org#11881-0 "Uterus Fundal height Tape measure"
* include http://terminology.hl7.org/CodeSystem/VHA#4688722 "FUNDAL HEIGHT"
* include http://loinc.org#32437-6 "Physical findings of Hearing"
* include http://terminology.hl7.org/CodeSystem/VHA#4688723 "HEARING"
* include http://loinc.org#8302-2 "Body height"
* include http://terminology.hl7.org/CodeSystem/VHA#4688724 "HEIGHT"
* include http://loinc.org#72514-3 "Pain severity - 0-10 verbal numeric rating [Score] - Reported"
* include http://terminology.hl7.org/CodeSystem/VHA#4500635 "PAIN"
* include http://loinc.org#8867-4 "Heart rate"
* include http://terminology.hl7.org/CodeSystem/VHA#4500636 "PULSE"
* include http://loinc.org#59408-5 "Oxygen saturation in Arterial blood by Pulse oximetry"
* include http://terminology.hl7.org/CodeSystem/VHA#4500637 "PULSE OXIMETRY"
* include http://loinc.org#2708-6 "Oxygen saturation in Arterial blood"
* include http://loinc.org#9279-1 "Respiratory rate"
* include http://terminology.hl7.org/CodeSystem/VHA#4688725 "RESPIRATION"
* include http://loinc.org#8310-5 "Body temperature"
* include http://terminology.hl7.org/CodeSystem/VHA#4500638 "TEMPERATURE"
* include http://loinc.org#28630-2 "Tonometry study"
* include http://terminology.hl7.org/CodeSystem/VHA#4688726 "TONOMETRY"
* include http://loinc.org#70936-0 "Vision testing Narrative"
* include http://terminology.hl7.org/CodeSystem/VHA#4688727 "VISION CORRECTED"
* include http://terminology.hl7.org/CodeSystem/VHA#4688728 "VISION UNCORRECTED"
* include http://loinc.org#29463-7 "Body weight"
* include http://terminology.hl7.org/CodeSystem/VHA#4500639 "WEIGHT"