ValueSet: VSVFRadiologyProcedureStatus
Title: "VF_RadiologyProcedureStatus"
Description: "Navigate to [ConceptMap VF_RadiologyProcedureStatus](ConceptMap-CMVFRadiologyProcedureStatus.html)"
* ^experimental = true
* ^name = "VF_RadiologyProcedureStatus"
* include urn:undefined#null "CALLED FOR EXAM"
* include urn:undefined#null "CANCELLED"
* include urn:undefined#null "COMPLETE"
* include urn:undefined#null "EXAMINED"
* include urn:undefined#null "TRANSCRIBED"
* include urn:undefined#null "WAITING FOR EXAM"
* include http://hl7.org/fhir/event-status#preparation "Preparation"
* include http://hl7.org/fhir/event-status#not-done "Not Done"
* include http://hl7.org/fhir/event-status#completed "Completed"
* include http://hl7.org/fhir/event-status#in-progress "In Progress"
* include http://hl7.org/fhir/event-status#in-progress "In Progress"
* include http://hl7.org/fhir/event-status#preparation "Preparation"