Instance: PHAPI
InstanceOf: CapabilityStatement
Title: "Lighthouse Patient Health API"
Usage: #definition
* description = "This CapabilityStatement enumerates the profiles that the API should address, in the estimation of the enterprise mapping team. Some elements may not be appropriate for those cases; consult the actual API specification published by the API provider"
* status = #draft
* date = "2025-05-12T19:54:20.105Z"
* kind = #requirements
* fhirVersion = #4.0.1
* format[0] = #xml
* format[1] = #json
* rest.mode = #server
* rest.resource[+].type = #AllergyIntolerance
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/AllergyIntolerance"
* rest.resource[+].type = #Patient
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Patient"
* rest.resource[+].type = #Appointment
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Appointment"
* rest.resource[+].type = #Condition
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ConditionProblem"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ConditionEncounterDiagnosis"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterInpatientCondition"
* rest.resource[+].type = #DiagnosticReport
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteSurgicalPathologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteElectronMicroscopyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteCytopathologyDiagnosticReport"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationDiagnosticReport"
* rest.resource[+].type = #Specimen
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteSurgicalPathologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserSpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteElectronMicroscopySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologySpecimen"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DiagnosticReportNoteCytopathologySpecimen"
* rest.resource[+].type = #Observation
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationChemhemtoxriaserObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservationbacteria"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservationurine"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservationsputum"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyBacteriologyObservationgramstain"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyParasitologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyObservationfungus"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservationmycobact"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyMycobacteriologyObservationacidfast"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyObservationvirus"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationMicrobiologyVirologyObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/LabObservationObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/SmokingStatusObservation"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSigns"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSignsBP"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/VitalSignsSpO2"
* rest.resource[+].type = #DocumentReference
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DocumentReferenceDocumentReference"
* rest.resource[+].type = #Binary
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/DocumentReferenceBinary"
* rest.resource[+].type = #Encounter
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterInpatientEncounter"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/EncounterOutpatient"
* rest.resource[+].type = #Immunization
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImmunizationImmunization"
* rest.resource[+].type = #Device
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDevice"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceALead"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceDental"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDevicePacemaker"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceProsthesis"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceTransmitter"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ImplantableDeviceVLead"
* rest.resource[+].type = #Location
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Location"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureSurgeryLocationOR"
* rest.resource[+].type = #MedicationRequest
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/MedicationRequestUnsigned"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/MedicationRequestNonVA"
* rest.resource[+].type = #Organization
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Organization"
* rest.resource[+].type = #Practitioner
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/Practitioner"
* rest.resource[+].type = #PractitionerRole
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/PractitionerRole"
* rest.resource[+].type = #Procedure
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureOutpatient"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureRadiology"
* rest.resource[=].supportedProfile[+] = "http://va.gov/fhir/StructureDefinition/ProcedureSurgeryProcedure"